INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(1,'Trek Distribution Inc.','Mark Johnson','(608) 555-1001','mark.johnson@trekdist.com','Madison','WI',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(2,'Electra Bicycle Co.','Lisa Chen','(760) 555-1002','lisa.chen@electrabike.com','Oceanside','CA',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(3,'Surly Parts Supply','Tom Olsen','(612) 555-1003','tom.olsen@surlysupply.com','Minneapolis','MN',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(4,'Haro Bikes Wholesale','Rachel Kim','(619) 555-1004','rachel.kim@harobikes.com','San Diego','CA',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(5,'Pure Cycles Direct','Carlos Rivera','(323) 555-1005','carlos@purecycles.com','Los Angeles','CA',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(6,'Ritchey Design Supply','Paul Ritchey','(650) 555-1006','paul@ritcheydesign.com','Redwood City','CA',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(7,'Strider Sports Int.','Ryan McFarland','(605) 555-1007','ryan@striderbikes.com','Rapid City','SD',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(8,'Sun Bicycle Wholesale','Dana Webb','(813) 555-1008','dana@sunbikes.com','Tampa','FL',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(9,'Heller Bikes Supply','Greg Heller','(503) 555-1009','greg@hellerbikes.com','Portland','OR',1);
INSERT INTO production_vendors(vendor_id, vendor_name, contact_name, phone, email, city, state, active) VALUES(10,'National Bike Imports','Sheila Park','(212) 555-1010','sheila@nbiimports.com','New York','NY',0);

INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(1,9);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(2,1);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(3,8);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(4,2);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(5,4);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(6,5);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(7,6);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(8,7);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(9,3);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(10,1);
INSERT INTO production_vendor_brands(vendor_id, brand_id) VALUES(10,2);
